module.exports = {
    participants: [],
    userUrl: 'https://randomuser.me/api/',
    inputName: document.getElementById('inputName'),
    btnGenerateName: document.getElementById('btnGenerateName'),
    inputMark: document.getElementById('inputMark'),
    btnGenerateMark: document.getElementById('btnGenerateMark'),
    inputAge: document.getElementById('inputAge'),
    btnGenerateAge: document.getElementById('btnGenerateAge'),
    inputSkills: document.getElementById('inputSkills'),
    btnGenerateSkills: document.getElementById('btnGenerateSkills'),
    inputEnglish: document.getElementById('inputEnglish'),
    btnGenerateEnglish: document.getElementById('btnGenerateEnglish'),
    btnGenerateAll: document.getElementById('btnGenerateAll'),
    btnAddParticipant: document.getElementById('btnAddParticipant'),
    btnShowParticipants: document.getElementById('btnShowParticipants'),
    btnStartRace: document.getElementById('btnStartRace'),
    btnClearParticipants: document.getElementById('btnClearParticipants'),
    canvas: document.getElementById('canvas'),
    ctx: canvas.getContext('2d'),
}